modLoader = "javafml"
loaderVersion = "[37,)"
license = "LGPL-3.0-only"

[[mods]]
 modId = "starlight"
 version = "1.0.0-RC3"
 displayName = "Starlight"
 authors = "Spottedleaf"
 description = '''
    Rewrites the light engine to fix lighting performance and lighting errors
 '''

 [[dependencies.starlight]]
  modId = "forge"
  mandatory = true
  versionRange = "[37,)"
  ordering = "NONE"
  side = "BOTH"

[[dependencies.starlight]]
  modId = "minecraft"
  mandatory = true
  versionRange = "[1.17, 1.18)"
  ordering = "NONE"
  side = "BOTH"